/**
 * Morning job: seeds daily MAG7 strike markets before market open.
 *
 * For each MAG7 ticker:
 *   1. Fetch previous close from Pyth Hermes
 *   2. Calculate strike prices (+/-3%, +/-6%, +/-9%, rounded)
 *   3. Create on-chain StrikeMarket for each strike
 *
 * Handles partial failures and retries with exponential backoff.
 * Intended to run at 8:00 AM ET on weekdays via cron.
 */

import * as anchor from "@coral-xyz/anchor";
import { PublicKey, Keypair, Connection } from "@solana/web3.js";
// KEY-DECISION 2026-03-09: import BN from bn.js directly, not anchor.BN.
// automation/ uses "type": "module" so `import * as anchor` gets ESM semantics
// where anchor.BN is undefined.
import BN from "bn.js";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import "dotenv/config";

import { calculateStrikes } from "./strikes.js";
import { fetchPrice, feedIdToBytes, DEFAULT_FEED_IDS } from "./pyth.js";

// IDL import - generated by anchor build
const idl = JSON.parse(
  readFileSync(new URL("../../target/idl/meridian.json", import.meta.url), "utf-8")
);

const MAG7_TICKERS = ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA"] as const;

const MAX_RETRIES = 3;
const BASE_DELAY_MS = 1000;

interface MarketResult {
  ticker: string;
  strikePrice: number;
  success: boolean;
  error?: string;
  txSignature?: string;
}

/**
 * Get today's trading day as UTC midnight timestamp (seconds).
 */
function getTradingDayTimestamp(): number {
  const now = new Date();
  const utcMidnight = new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())
  );
  return Math.floor(utcMidnight.getTime() / 1000);
}

/**
 * Get today's 4:00 PM ET as a UTC unix timestamp (seconds).
 * ET is UTC-5 (EST) or UTC-4 (EDT). We approximate by checking DST.
 */
function getCloseTimeTimestamp(): number {
  const now = new Date();
  // Create a date for today at 16:00 ET
  // Use America/New_York to handle DST automatically
  // EST = UTC-5, EDT = UTC-4. Rough DST check (March-November).
  const month = now.getUTCMonth(); // 0-indexed
  const isDST = month >= 2 && month <= 10;
  const etOffset = isDST ? 4 : 5;

  const closeHourUTC = 16 + etOffset;
  const closeDate = new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(), closeHourUTC, 0, 0)
  );
  return Math.floor(closeDate.getTime() / 1000);
}

/**
 * Convert a dollar strike price to USDC base units (6 decimals).
 * $680.00 -> 680_000_000
 */
function dollarToUsdcBaseUnits(dollars: number): BN {
  return new BN(Math.round(dollars * 1_000_000));
}

/**
 * Sleep for a given number of milliseconds.
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Load the admin keypair from a JSON file.
 */
function loadAdminKeypair(): Keypair {
  const keypairPath = resolve(
    process.env.ADMIN_KEYPAIR_PATH || ".wallets/admin.json"
  );
  const expanded = keypairPath.replace(/^~/, process.env.HOME || "");
  const secretKey = JSON.parse(readFileSync(expanded, "utf-8"));
  return Keypair.fromSecretKey(Uint8Array.from(secretKey));
}

/**
 * Create a single strike market on-chain with retry logic.
 */
async function createMarketWithRetry(
  program: anchor.Program,
  admin: Keypair,
  usdcMint: PublicKey,
  ticker: string,
  strikePriceDollars: number,
  date: BN,
  closeTime: BN,
  pythFeedId: number[]
): Promise<MarketResult> {
  const strikePriceBaseUnits = dollarToUsdcBaseUnits(strikePriceDollars);

  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      const sig = await program.methods
        .createStrikeMarket(
          ticker,
          strikePriceBaseUnits,
          date,
          closeTime,
          pythFeedId
        )
        .accountsPartial({
          admin: admin.publicKey,
          usdcMint: usdcMint,
        })
        .signers([admin])
        .rpc();

      console.log(
        `[ok] ${ticker} @ $${strikePriceDollars} -> tx: ${sig}`
      );

      return {
        ticker,
        strikePrice: strikePriceDollars,
        success: true,
        txSignature: sig,
      };
    } catch (err: any) {
      const errMsg = err?.message || String(err);

      // If the account already exists (market already created), treat as success
      if (errMsg.includes("already in use") || errMsg.includes("0x0")) {
        console.log(
          `[skip] ${ticker} @ $${strikePriceDollars} - market already exists`
        );
        return {
          ticker,
          strikePrice: strikePriceDollars,
          success: true,
        };
      }

      if (attempt < MAX_RETRIES) {
        const delay = BASE_DELAY_MS * Math.pow(2, attempt - 1);
        console.warn(
          `[retry] ${ticker} @ $${strikePriceDollars} attempt ${attempt}/${MAX_RETRIES} failed: ${errMsg}. Retrying in ${delay}ms...`
        );
        await sleep(delay);
      } else {
        console.error(
          `[fail] ${ticker} @ $${strikePriceDollars} failed after ${MAX_RETRIES} attempts: ${errMsg}`
        );
        return {
          ticker,
          strikePrice: strikePriceDollars,
          success: false,
          error: errMsg,
        };
      }
    }
  }

  // Unreachable, but TypeScript needs it
  return { ticker, strikePrice: strikePriceDollars, success: false, error: "unreachable" };
}

/**
 * Run the morning job: fetch prices, calculate strikes, create markets.
 */
export async function runMorningJob(): Promise<void> {
  console.log(`\n=== Morning Job Started at ${new Date().toISOString()} ===\n`);

  // Load configuration
  const rpcUrl = process.env.RPC_URL || "https://api.devnet.solana.com";
  const programId = new PublicKey(
    process.env.PROGRAM_ID || "GMwKXYNKRkN3wGdgAwR4BzG2RfPGGLGjehuoNwUzBGk2"
  );
  const usdcMint = new PublicKey(process.env.USDC_MINT || PublicKey.default);
  const hermesUrl = process.env.HERMES_URL || "https://hermes.pyth.network";

  // Parse optional feed ID overrides
  let feedIds = { ...DEFAULT_FEED_IDS };
  if (process.env.PYTH_FEED_OVERRIDES) {
    try {
      const overrides = JSON.parse(process.env.PYTH_FEED_OVERRIDES);
      feedIds = { ...feedIds, ...overrides };
    } catch {
      console.warn("[warn] Failed to parse PYTH_FEED_OVERRIDES, using defaults");
    }
  }

  // Setup Anchor
  const connection = new Connection(rpcUrl, "confirmed");
  const admin = loadAdminKeypair();
  const wallet = new anchor.Wallet(admin);
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });

  const program = new anchor.Program(idl as anchor.Idl, provider);

  // Timestamps for today
  const date = new BN(getTradingDayTimestamp());
  const closeTime = new BN(getCloseTimeTimestamp());

  console.log(`Trading date: ${new Date(date.toNumber() * 1000).toISOString().slice(0, 10)}`);
  console.log(`Close time:   ${new Date(closeTime.toNumber() * 1000).toISOString()}`);
  console.log(`RPC:          ${rpcUrl}`);
  console.log(`Program:      ${programId.toBase58()}`);
  console.log(`Admin:        ${admin.publicKey.toBase58()}\n`);

  const allResults: MarketResult[] = [];

  for (const ticker of MAG7_TICKERS) {
    try {
      // 1. Fetch previous close
      const { price: previousClose } = await fetchPrice(ticker, feedIds, hermesUrl);
      console.log(`\n[${ticker}] Previous close: $${previousClose.toFixed(2)}`);

      // 2. Calculate strikes
      const strikes = calculateStrikes(previousClose);
      console.log(`[${ticker}] Strikes: ${strikes.map((s) => `$${s}`).join(", ")}`);

      // 3. Get Pyth feed ID bytes for on-chain storage
      const pythFeedId = feedIdToBytes(feedIds[ticker]);

      // 4. Create markets for each strike
      for (const strikePriceDollars of strikes) {
        const result = await createMarketWithRetry(
          program,
          admin,
          usdcMint,
          ticker,
          strikePriceDollars,
          date,
          closeTime,
          pythFeedId
        );
        allResults.push(result);
      }
    } catch (err) {
      console.error(`[fail] ${ticker} - skipping entirely: ${err}`);
    }
  }

  // Summary
  const succeeded = allResults.filter((r) => r.success).length;
  const failed = allResults.filter((r) => !r.success).length;

  console.log(`\n=== Morning Job Complete ===`);
  console.log(`Markets created: ${succeeded} succeeded, ${failed} failed out of ${allResults.length} total`);

  if (failed > 0) {
    console.log(`\nFailed markets:`);
    for (const r of allResults.filter((r) => !r.success)) {
      console.log(`  ${r.ticker} @ $${r.strikePrice}: ${r.error}`);
    }
  }

  console.log("");
}

// Allow direct execution
const isDirectRun =
  process.argv[1]?.endsWith("morning-job.ts") ||
  process.argv[1]?.endsWith("morning-job.js");

if (isDirectRun) {
  runMorningJob().catch((err) => {
    console.error("Morning job failed:", err);
    process.exit(1);
  });
}
