import { PublicKey } from "@solana/web3.js";

// Try to load local config generated by scripts/setup-local.ts
// This file is gitignored and only exists in local dev
let localMint: string | null = null;
try {
  const config = await import("./local-config.json");
  localMint = config.usdcMint ?? config.default?.usdcMint ?? null;
} catch {
  // No local config - expected on devnet
}

const mintAddress =
  localMint ||
  (import.meta.env.VITE_USDC_MINT as string | undefined) ||
  null;

export function useUsdcMint(): PublicKey {
  if (!mintAddress) {
    throw new Error(
      "USDC mint not configured. Run `make setup` or set VITE_USDC_MINT."
    );
  }
  return new PublicKey(mintAddress);
}
