/**
 * Settlement job: settles MAG7 strike markets after market close.
 *
 * 1. Pauses minting via GlobalConfig
 * 2. Finds all unsettled (Pending) markets
 * 3. Tries settle_market (Pyth pull oracle, no delay), falls back to admin_settle (1hr delay)
 * 4. Retries admin_settle on confidence failures for up to 15 minutes
 * 5. Unpauses after all settlements complete
 *
 * Intended to run at 4:07 PM ET on weekdays (7 min after market close).
 */

import * as anchor from "@coral-xyz/anchor";
import { PublicKey, Keypair, Connection, AccountMeta } from "@solana/web3.js";
// KEY-DECISION 2026-03-09: import BN from bn.js directly, not anchor.BN.
// automation/ uses "type": "module" so `import * as anchor` gets ESM semantics
// where anchor.BN is undefined.
import BN from "bn.js";
import { readFileSync } from "node:fs";
import path from "node:path";

import { fetchPrice, PYTH_FEED_IDS } from "./pyth";
import { oracleSettle } from "./pyth-settle";
import { sendAlert } from "./alert";

// IDL import - generated by anchor build
const idl = JSON.parse(
  readFileSync(path.join(import.meta.dirname, "../target/idl/meridian.json"), "utf-8")
);

const RETRY_INTERVAL_MS = 30_000; // 30 seconds
const MAX_RETRY_DURATION_MS = 15 * 60 * 1000; // 15 minutes
const MARKET_SETTLE_DELAY_MS = Number(process.env.MARKET_SETTLE_DELAY_MS || "1500");
const RPC_429_BASE_DELAY_MS = Number(process.env.RPC_429_BASE_DELAY_MS || "1000");
const MAX_RPC_429_RETRIES = Number(process.env.MAX_RPC_429_RETRIES || "4");

interface SettlementResult {
  market: string; // pubkey base58
  ticker: string;
  strikePrice: number;
  success: boolean;
  method?: "settle_market" | "admin_settle";
  error?: string;
  txSignature?: string;
}

/**
 * Sleep for a given number of milliseconds.
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Load the admin keypair from a JSON file.
 */
function loadAdminKeypair(): Keypair {
  const keypairPath = process.env.ADMIN_KEYPAIR_PATH || ".wallets/admin.json";
  const expanded = keypairPath.replace(/^~/, process.env.HOME || "");
  const secretKey = JSON.parse(readFileSync(expanded, "utf-8"));
  return Keypair.fromSecretKey(Uint8Array.from(secretKey));
}

/**
 * Derive the GlobalConfig PDA.
 */
function getConfigPda(programId: PublicKey): PublicKey {
  const [pda] = PublicKey.findProgramAddressSync(
    [Buffer.from("config")],
    programId
  );
  return pda;
}

/**
 * Check if an Anchor enum variant matches a given name.
 * Anchor represents enums as objects like { pending: {} } or { yesWins: {} }.
 */
function isOutcomePending(outcome: Record<string, unknown>): boolean {
  return "pending" in outcome;
}

/**
 * Convert a dollar price to USDC base units (6 decimals).
 */
function dollarToUsdcBaseUnits(dollars: number): BN {
  return new BN(Math.round(dollars * 1_000_000));
}

function marketCloseTimeSeconds(marketAccount: any): number | null {
  const raw = marketAccount.closeTime;
  if (raw == null) return null;
  if (typeof raw === "number") return raw;
  if (typeof raw?.toNumber === "function") return raw.toNumber();
  return null;
}

function adminSettleEligible(marketAccount: any, nowSeconds: number): boolean {
  const closeTime = marketCloseTimeSeconds(marketAccount);
  if (closeTime == null) return true;
  return nowSeconds >= closeTime + 3600;
}

function isRpc429(errMsg: string): boolean {
  return errMsg.includes("429") || errMsg.toLowerCase().includes("rate limited");
}

/**
 * Attempt to settle a single market. Tries settle_market (oracle) first, then
 * admin_settle. Retries on confidence-related failures for up to MAX_RETRY_DURATION_MS.
 */
async function settleMarketWithRetry(
  program: anchor.Program,
  admin: Keypair,
  connection: Connection,
  marketPubkey: PublicKey,
  marketAccount: any,
  feedIds: Record<string, string>,
  hermesUrl: string
): Promise<SettlementResult> {
  const ticker = marketAccount.ticker || "UNKNOWN";
  const strikeDollars = (marketAccount.strikePrice as BN).toNumber() / 1_000_000;
  const marketKey = marketPubkey.toBase58();

  const startTime = Date.now();

  // --- Attempt 1: settle_market (permissionless, Pyth pull oracle, no 1hr delay) ---
  // Posts a PriceUpdateV2 account via Wormhole-verified VAA from Hermes, then
  // calls settle_market. Tried once before falling back to the admin_settle loop.
  const closeTime = marketCloseTimeSeconds(marketAccount);
  const feedId = feedIds[ticker];
  if (closeTime !== null && feedId) {
    try {
      const sig = await oracleSettle(
        connection,
        admin,
        program,
        marketPubkey,
        feedId,
        closeTime,
        hermesUrl
      );
      console.log(`[ok] ${ticker} @ $${strikeDollars} settled via oracle (tx: ${sig})`);
      return {
        market: marketKey,
        ticker,
        strikePrice: strikeDollars,
        success: true,
        method: "settle_market",
        txSignature: sig,
      };
    } catch (oracleErr: any) {
      const oracleErrMsg = oracleErr?.message || String(oracleErr);
      if (
        oracleErrMsg.includes("already settled") ||
        oracleErrMsg.includes("MarketAlreadySettled")
      ) {
        console.log(`[skip] ${ticker} @ $${strikeDollars} - already settled`);
        return {
          market: marketKey,
          ticker,
          strikePrice: strikeDollars,
          success: true,
          method: "settle_market",
        };
      }
      console.warn(
        `[oracle] ${ticker} @ $${strikeDollars} - oracle path failed, falling back to admin_settle: ${oracleErrMsg.slice(0, 160)}`
      );
      // Alert so operators know the oracle path is failing and why.
      // Expected during devnet setup (before HERMES_URL=hermes-beta and post-market feeds);
      // should NOT fire on a properly configured environment.
      await sendAlert(
        "settlement-job",
        `settle_market failed for ${ticker} @ $${strikeDollars}, falling back to admin_settle: ${oracleErrMsg.slice(0, 200)}`
      );
    }
  }

  // --- Attempt 2: admin_settle with Hermes price ---
  // Requires close_time + 3600s (1hr delay). Retries on confidence failures.
  while (true) {
    const elapsed = Date.now() - startTime;
    const nowSeconds = Math.floor(Date.now() / 1000);

    if (!adminSettleEligible(marketAccount, nowSeconds)) {
      console.warn(
        `[skip] ${ticker} @ $${strikeDollars} - too early for admin_settle (1hr delay not met)`
      );
      return {
        market: marketKey,
        ticker,
        strikePrice: strikeDollars,
        success: false,
        error: "Too early for admin_settle - 1hr delay not met",
      };
    }

    try {
      const { price: dollarPrice, confidence } = await fetchPrice(ticker, feedIds, hermesUrl);

      // Check confidence: reject if band > 1% of price
      const confidenceRatio = confidence / dollarPrice;
      if (confidenceRatio > 0.01) {
        if (elapsed + RETRY_INTERVAL_MS > MAX_RETRY_DURATION_MS) {
          console.error(
            `[fail] ${ticker} @ $${strikeDollars} - confidence too wide after ${Math.round(elapsed / 1000)}s: ${(confidenceRatio * 100).toFixed(2)}% > 1%`
          );
          return {
            market: marketKey,
            ticker,
            strikePrice: strikeDollars,
            success: false,
            error: `Confidence too wide: ${(confidenceRatio * 100).toFixed(2)}%`,
          };
        }
        console.warn(
          `[retry] ${ticker} @ $${strikeDollars} - confidence ${(confidenceRatio * 100).toFixed(2)}% > 1%, retrying in ${RETRY_INTERVAL_MS / 1000}s...`
        );
        await sleep(RETRY_INTERVAL_MS);
        continue;
      }

      const priceBaseUnits = dollarToUsdcBaseUnits(dollarPrice);
      console.log(
        `[settle] ${ticker} @ $${strikeDollars} - Pyth price: $${dollarPrice.toFixed(2)} (${priceBaseUnits.toString()} base units)`
      );

      // Derive OrderBook PDA so auto_credit_resting_orders can credit makers
      const [orderBookPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("orderbook"), marketPubkey.toBuffer()],
        program.programId
      );
      const remainingAccounts: AccountMeta[] = [
        { pubkey: orderBookPda, isSigner: false, isWritable: true },
      ];

      let sig: string | null = null;
      for (let attempt = 0; attempt <= MAX_RPC_429_RETRIES; attempt++) {
        try {
          sig = await program.methods
            .adminSettle(priceBaseUnits)
            .accountsPartial({
              admin: admin.publicKey,
              market: marketPubkey,
            })
            .remainingAccounts(remainingAccounts)
            .signers([admin])
            .rpc();
          break;
        } catch (rpcErr: any) {
          const rpcErrMsg = rpcErr?.message || String(rpcErr);
          if (!isRpc429(rpcErrMsg) || attempt === MAX_RPC_429_RETRIES) {
            throw rpcErr;
          }
          const delayMs = RPC_429_BASE_DELAY_MS * Math.pow(2, attempt);
          console.warn(
            `[retry] ${ticker} @ $${strikeDollars} - RPC rate limited, retrying admin_settle in ${delayMs}ms...`
          );
          await sleep(delayMs);
        }
      }

      if (!sig) {
        throw new Error("admin_settle did not produce a transaction signature");
      }

      const outcome = dollarPrice >= strikeDollars ? "YesWins" : "NoWins";
      console.log(
        `[ok] ${ticker} @ $${strikeDollars} settled -> ${outcome} (tx: ${sig})`
      );

      return {
        market: marketKey,
        ticker,
        strikePrice: strikeDollars,
        success: true,
        method: "admin_settle",
        txSignature: sig,
      };
    } catch (err: any) {
      const errMsg = err?.message || String(err);

      // Already settled
      if (errMsg.includes("already settled") || errMsg.includes("MarketAlreadySettled")) {
        console.log(`[skip] ${ticker} @ $${strikeDollars} - already settled`);
        return {
          market: marketKey,
          ticker,
          strikePrice: strikeDollars,
          success: true,
          method: "admin_settle",
        };
      }

      // admin_settle requires close_time + 3600 < now
      if (errMsg.includes("TooEarlyForAdminSettle") || errMsg.includes("too early")) {
        console.warn(
          `[skip] ${ticker} @ $${strikeDollars} - too early for admin_settle (1hr delay not met)`
        );
        return {
          market: marketKey,
          ticker,
          strikePrice: strikeDollars,
          success: false,
          error: "Too early for admin_settle - 1hr delay not met",
        };
      }

      // Confidence-related retry
      if (errMsg.includes("confidence") || errMsg.includes("stale")) {
        if (elapsed + RETRY_INTERVAL_MS > MAX_RETRY_DURATION_MS) {
          console.error(
            `[fail] ${ticker} @ $${strikeDollars} - oracle error after ${Math.round(elapsed / 1000)}s: ${errMsg}`
          );
          return {
            market: marketKey,
            ticker,
            strikePrice: strikeDollars,
            success: false,
            error: errMsg,
          };
        }
        console.warn(
          `[retry] ${ticker} @ $${strikeDollars} - ${errMsg}, retrying in ${RETRY_INTERVAL_MS / 1000}s...`
        );
        await sleep(RETRY_INTERVAL_MS);
        continue;
      }

      // Non-retryable error
      console.error(`[fail] ${ticker} @ $${strikeDollars} - ${errMsg}`);
      return {
        market: marketKey,
        ticker,
        strikePrice: strikeDollars,
        success: false,
        error: errMsg,
      };
    }
  }
}

/**
 * Run the settlement job: pause, settle all pending markets, unpause.
 */
export async function runSettlementJob(): Promise<void> {
  console.log(`\n=== Settlement Job Started at ${new Date().toISOString()} ===\n`);

  try {
    // Load configuration
    const rpcUrl = process.env.RPC_URL || "https://api.devnet.solana.com";
    const programId = new PublicKey(
      process.env.PROGRAM_ID || (idl as { address: string }).address
    );
    const hermesUrl = process.env.HERMES_URL || "https://hermes.pyth.network";

    // Parse optional feed ID overrides
    let feedIds = { ...PYTH_FEED_IDS };
    if (process.env.PYTH_FEED_OVERRIDES) {
      try {
        const overrides = JSON.parse(process.env.PYTH_FEED_OVERRIDES);
        feedIds = { ...feedIds, ...overrides };
      } catch {
        console.warn("[warn] Failed to parse PYTH_FEED_OVERRIDES, using defaults");
      }
    }

    // Setup Anchor
    const connection = new Connection(rpcUrl, "confirmed");
    const admin = loadAdminKeypair();
    const wallet = new anchor.Wallet(admin);
    const provider = new anchor.AnchorProvider(connection, wallet, {
      commitment: "confirmed",
    });

    const program = new anchor.Program(idl as anchor.Idl, provider);
    const configPda = getConfigPda(programId);

    console.log(`RPC:     ${rpcUrl}`);
    console.log(`Program: ${programId.toBase58()}`);
    console.log(`Admin:   ${admin.publicKey.toBase58()}`);
    console.log(`Config:  ${configPda.toBase58()}\n`);

    // Step 1: Pause minting
    console.log("[pause] Pausing minting...");
    try {
      const pauseSig = await program.methods
        .pause()
        .accountsPartial({
          admin: admin.publicKey,
          config: configPda,
        })
        .signers([admin])
        .rpc();
      console.log(`[ok] Minting paused (tx: ${pauseSig})`);
    } catch (err: any) {
      const errMsg = err?.message || String(err);
      if (errMsg.includes("already paused") || errMsg.includes("AlreadyPaused")) {
        console.log("[skip] Already paused");
      } else {
        console.error(`[fail] Failed to pause: ${errMsg}`);
        // Continue anyway - settlement is more important than pausing
      }
    }

    // Step 2: Find all unsettled markets
    console.log("\n[scan] Fetching all markets...");
    const allMarkets = await (program.account as any).strikeMarket.all();
    const pendingMarkets = allMarkets.filter((m: any) =>
      isOutcomePending(m.account.outcome as Record<string, unknown>)
    );

    console.log(
      `[scan] Found ${allMarkets.length} total markets, ${pendingMarkets.length} pending settlement\n`
    );

    if (pendingMarkets.length === 0) {
      console.log("[skip] No markets to settle");
    }

    // Step 3: Settle each pending market
    const results: SettlementResult[] = [];
    for (const { publicKey, account } of pendingMarkets) {
      const result = await settleMarketWithRetry(
        program,
        admin,
        connection,
        publicKey,
        account,
        feedIds,
        hermesUrl
      );
      results.push(result);
      await sleep(MARKET_SETTLE_DELAY_MS);
    }

    // Step 4: Unpause
    console.log("\n[unpause] Unpausing minting...");
    try {
      const unpauseSig = await program.methods
        .unpause()
        .accountsPartial({
          admin: admin.publicKey,
          config: configPda,
        })
        .signers([admin])
        .rpc();
      console.log(`[ok] Minting unpaused (tx: ${unpauseSig})`);
    } catch (err: any) {
      const errMsg = err?.message || String(err);
      if (errMsg.includes("not paused") || errMsg.includes("NotPaused")) {
        console.log("[skip] Already unpaused");
      } else {
        console.error(`[fail] Failed to unpause: ${errMsg}`);
      }
    }

    // Summary
    const succeeded = results.filter((r) => r.success).length;
    const failed = results.filter((r) => !r.success).length;

    console.log(`\n=== Settlement Job Complete ===`);
    console.log(
      `Settled: ${succeeded} succeeded, ${failed} failed out of ${results.length} total`
    );

    if (failed > 0) {
      console.log(`\nFailed markets:`);
      for (const r of results.filter((r) => !r.success)) {
        console.log(`  ${r.ticker} @ $${r.strikePrice} (${r.market}): ${r.error}`);
      }
      console.log(
        "\nHint: Use admin_settle manually for failed markets after the 1-hour delay window."
      );
      await sendAlert(
        "settlement-job",
        `${failed}/${results.length} markets failed to settle. Check container logs.`
      );
    }

    console.log("");
  } catch (err) {
    console.error(`[fatal] Settlement job encountered an unexpected error: ${err}`);
    await sendAlert("settlement-job", `Fatal error: ${err}`);
    // Never throw - the job should report and exit cleanly
  }
}

// Allow direct execution
const isDirectRun =
  process.argv[1]?.endsWith("settlement-job.ts") ||
  process.argv[1]?.endsWith("settlement-job.js");

if (isDirectRun) {
  runSettlementJob().catch((err) => {
    console.error("Settlement job failed:", err);
    process.exit(1);
  });
}
