import { PublicKey } from "@solana/web3.js";
import idl from "../idl/meridian.json";

const viteEnv = (import.meta as ImportMeta & {
  env?: Record<string, string | undefined>;
}).env ?? {};
const browserHostname = typeof window !== "undefined" ? window.location.hostname : null;
const isLocalBrowser =
  browserHostname === "localhost" || browserHostname === "127.0.0.1";

// Program ID: single source of truth is the IDL (generated by anchor build).
// Override with VITE_PROGRAM_ID env var for non-standard deploys.
export const PROGRAM_ID = new PublicKey(
  viteEnv.VITE_PROGRAM_ID || idl.address
);

// Vite exposes env vars prefixed with VITE_
// Default to localhost for local dev, override with VITE_RPC_URL for devnet
export const RPC_URL =
  viteEnv.VITE_RPC_URL || (isLocalBrowser ? "http://127.0.0.1:8899" : "http://localhost:8899");

export const IS_LOCAL_RPC =
  RPC_URL.includes("localhost") || RPC_URL.includes("127.0.0.1");
export const IS_REMOTE_RPC = !IS_LOCAL_RPC;


export const RPC_MODE_LABEL = IS_LOCAL_RPC ? "Local validator" : "Remote RPC";
export const ACTIVITY_LIMIT = IS_LOCAL_RPC ? 120 : 12;

export const PORTFOLIO_SIGNATURE_LIMIT = IS_LOCAL_RPC ? 120 : 12;

// MAG7 tickers and their Pyth Hermes price feed IDs (equity feeds)
export const MAG7 = [
  {
    ticker: "AAPL",
    name: "Apple",
    pythFeedId:
      "0x49f6b65cb1de6b10eaf75e7c03ca029c306d0357e91b5311b175084a5ad55688",
  },
  {
    ticker: "MSFT",
    name: "Microsoft",
    pythFeedId:
      "0xd0ca23c1cc005e004ccf1db5bf76aeb6a49218f43dac3d4b275e92de12ded4d1",
  },
  {
    ticker: "GOOGL",
    name: "Alphabet",
    pythFeedId:
      "0x5a48c03e9b9cb337801073ed9d166817473697efff0d138874e0f6a33d6d5aa6",
  },
  {
    ticker: "AMZN",
    name: "Amazon",
    pythFeedId:
      "0xb5d0e0fa58a1f8b81498ae670ce93c872d14434b72c364885d4fa1b257cbb07a",
  },
  {
    ticker: "NVDA",
    name: "NVIDIA",
    pythFeedId:
      "0xb1073854ed24cbc755dc527418f52b7d271f6cc967bbf8d8129112b18860a593",
  },
  {
    ticker: "META",
    name: "Meta Platforms",
    pythFeedId:
      "0x78a3e3b8e676a8f73c439f5d749737034b139bbbe899ba5775216fba596607fe",
  },
  {
    ticker: "TSLA",
    name: "Tesla",
    pythFeedId:
      "0x16dad506d7db8da01c87581c87ca897a012a153557d4d578c3b9c9e1bc0632f1",
  },
] as const;

export type Ticker = (typeof MAG7)[number]["ticker"];

// USDC uses 6 decimal places
export const USDC_DECIMALS = 6;
export const USDC_PER_PAIR = 1_000_000; // 1.00 USDC in base units
